speculos.py
`--seed` arg actually expected a BIP39 mnemonic, not a seed.
This PR allows using real BIP39 seeds with this same arg, by prefixing it with `hex:`
eg:
`--seed abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about`
is equivalent to 
`--seed hex:5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4`
Use case:
As going from mnemonic to seed is done through a one way function (PBKDF2), there are a few cases where we only have access to the seed, but we can't recompute the source mnemonic from it.
=> Add BIP39 hex seed support

speculos.py, src/launcher.c
Additional ram page address & size now read from ELF file. If provided on the CLI by the user, parameters -q & -r will supersede the values from the ELF file.
=> LVFM-328: bssrf section address and size read from elf file

CMakeLists.txt
Specify project language, to avoid cmake trying to find C++ compiler.
=> Do not require C++

tools/ledger-live-http-proxy.py
This makes it possible to access this server from web page running on different origin (host / port).
=> Allow CORS in ledger-live-http-proxy

mcu/seproxyhal.py
Without this fix, `PRINTF` are displayed char by char by Speculos.
=> Fix PRINTF multiline issue

CMakeLists.txt, Dockerfile.build
`openssl-1.1.1d` is no more available at https://www.openssl.org/source/openssl-1.1.1d.tar.gz, the building process was failing:
> -- Downloading...
>    dst='/speculos/build/openssl-prefix/src/openssl-1.1.1d.tar.gz'
>    timeout='none'
> -- Using src='https://www.openssl.org/source/openssl-1.1.1d.tar.gz'
> -- Retrying...
> -- Using src='https://www.openssl.org/source/openssl-1.1.1d.tar.gz'
> -- Retry after 5 seconds (attempt #2) ...
> -- Using src='https://www.openssl.org/source/openssl-1.1.1d.tar.gz'
> -- Retry after 5 seconds (attempt #3) ...
So I updated it to the latest version `openssl-1.1.1f`.
=> openssl update

vnc/CMakeLists.txt, vnc/seccomp-bpf.h, vnc/vnc_server.c
Fixes #45.
TODO: ensure other teams add `libseccomp-dev` to their dependencies
=> vnc: sandbox the server using seccomp-bpf

src/emu_default.c, src/emu_os_1.5.c, src/emu_os_1.6.c, src/emulate.c, src/emulate.h, src/emulate_1.5.c, src/emulate_1.6.c, src/emulate_blue_2.2.5.c
A few syscalls return BOLOS_UX_OK whose value changed over time:
- SDK 1.5: 0xB0105011
- SDK 1.6: 0xAA
=> fix BOLOS_UX_OK with SDK 1.6

doc/usage.md
List the SDK version strings supported by speculos' `-k` argument. It is all in the code, but it's better if that info can be found in the doc instead :-).
=> Add details about supported SDK versions

src/cx_ec.c
Fix a warning reported by lgtm.com about an empty `if` block, and add proper `const` qualifiers.
=> cx_ec cleanup

CMakeLists.txt, doc/tests.md
Using code coverage makes is easier to find out what is tested by running `make -C build test`.
After this PR, it is possible to integrate Speculos CI with https://codecov.io in order to compare the code coverage of tests for each PR. I have done this in https://codecov.io/gh/niooss-ledger/speculos and I will clean up my changes and submit them, once this PR is reviewed and merged.
=> Add code coverage instrumentation using option to CMake

src/cx_hash.h, src/emulate.c
Duplicated existing `cx_sha256_init()` syscall.
=> enable `cx_sha512_init()` syscall

tests/syscalls/test_bip32.c
cmocka supports `fail()` to fail immediately: https://api.cmocka.org/group__cmocka__exec.html
This is nicer for static analyzers, as using a function that is known to never return enables them to understand that variables `mode` and `curve` are always initialized in `test_bolos_vector`.
=> Use fail() instead of assert_true(false) in test_bip32

src/cx_blake2b.c
clang reports the following warnings when building speculos:
[  2%] Building C object src/CMakeFiles/emu.dir/cx_blake2b.c.o
/code/src/cx_blake2b.c:158:31: warning: unused function 'load32' [-Wunused-function]
static BLAKE2_INLINE uint32_t load32( const void *src )
^
/code/src/cx_blake2b.c:192:31: warning: unused function 'load16' [-Wunused-function]
static BLAKE2_INLINE uint16_t load16( const void *src )
^
/code/src/cx_blake2b.c:205:27: warning: unused function 'store16' [-Wunused-function]
static BLAKE2_INLINE void store16( void *dst, uint16_t w )
^
/code/src/cx_blake2b.c:246:31: warning: unused function 'load48' [-Wunused-function]
static BLAKE2_INLINE uint64_t load48( const void *src )
^
/code/src/cx_blake2b.c:257:27: warning: unused function 'store48' [-Wunused-function]
static …
=> Remove unused functions from Blake2b implementation

build.Dockerfile
curl is used by the GitHub action for codecov.io integration.
While at it, optimize the layer building of the Dockerfile.
`docker images` reports the following sizes:
* Before this commit: 1.36 GB
* With curl, moving `apt-get clean` near `apt-get install`: 1.32 GB
* With `tar x && build && install && remove sources` in one step: 985 MB
=> Install curl in speculos-builder and optimize the Dockerfile

.github/workflows/continuous-integration-workflow.yml
This produces nice coverage reports such as https://codecov.io/gh/niooss-ledger/speculos
NB. This Pull Request requires `curl` to be available in `ledgerhq/speculos-builder` Docker image, so https://github.com/LedgerHQ/speculos/pull/79 has to be reviewed and merged before.
=> Push code coverage to codecov.io, in GitHub actions

.github/workflows/continuous-integration-workflow.yml, doc/tests.md, src/emu_cx.c, src/emulate.h, src/launcher.c, tests/syscalls/test_ecdsa.c
* Force the seed when running the code coverage, using `RNG_SEED` environment varible.
* Use `RAND_set_rand_method()` to make `RAND_bytes()` get random bytes from the same PRNG as `sys_cx_rng()`
The aim of this Pull Request is to fix blinking in code coverage analysis such as https://codecov.io/gh/LedgerHQ/speculos/pull/86/changes
=> Make the code coverage deterministic

src/cx_ec.c, tests/syscalls/test_ecdsa.c
The RFC6979 deterministic signature implementation in Speculos is not compatible with hash functions that have a variable output length, because they rely on this function to compute HMAC:
int cx_hmac_init(cx_hmac_ctx *ctx, cx_md_t hash_id, const uint8_t *key,
size_t key_len)
In order to support variable-output-size digests, the digest size has to be specified, for example with a new `size_t output_size` parameter, like what was done for `cx_hash_init_ex`.
Instead of changing the API, keep the behaviour of `cx_ecdsa_sign(CX_RND_RFC6979, CX_BLAKE2B)` failing with `THROW(INVALID_PARAMETER);` and fix `cx_ecdsa_sign(CX_RND_TRNG, CX_BLAKE2B)` to make it work again
(with a weak PRNG used to make tests deterministics).
Fixes: https://github.com/LedgerHQ/speculos/issues/90
=> Do not use RFC6979 signature with variable-length hashes

src/cx_ec.c, tests/syscalls/test_ecdsa.c
This is needed to implement recoverable ECDSA signature, for example in Tron app: https://github.com/LedgerHQ/speculos/issues/93
Test recovering the public key in tests. As there is no known test vectors for this feature (and libraries like libsecp256k1 generates
random messages and keys in their tests, like https://github.com/ethereum/go-ethereum/blob/v1.9.19/crypto/secp256k1/libsecp256k1/src/modules/recovery/tests_impl.h#L161), implement ECDSA public key recovery using OpenSSL.
=> Fill ECDSA signature information in cx_ecdsa_sign

vnc/vnc_server.c
=> vnc: add gettimeofday to the seccomp filter

docker-compose.yml
**Issue #100**
`docker-compose.yml` wasn't updated when we started using dockerhub image.
**Try it**
`docker-compose up`
=> docker-compose now uses dockerhub image container

src/emulate_1.5.c, src/emulate_1.6.c, src/emulate_blue_2.2.5.c
The cx_aes_iv syscall number is indeed different in the SDK 1.6 than in
1.5 and Blue.
=> Fix the cx_aes_iv syscall for SDK 1.6

src/CMakeLists.txt, src/cx_curve25519.c, src/cx_curve25519.h, src/cx_ec.c, tests/syscalls/test_ec.c
This patch implements scalar multiplication on Curve25519 for the `cx_ecfp_scalar_mult` syscall.
I am not completely found of the implementation, because it copy/past the OpenSSL implementation. The issue is that the publicly accessible `X25519` function isn't a "clean" scalar multiplication per se, because it applies the "DJB" recommendations on the scalar bytes (https://github.com/openssl/openssl/blob/master/crypto/ec/curve25519.c#L4384). Please let me know if you see a "cleaner" way to do this :)
=> Implement scalar multiplication on Curve25519

mcu/headless.py, mcu/readerror.py, mcu/screen.py, mcu/screen_text.py, mcu/seproxyhal.py
When you select Quit in the App with the down key, the program was doing a sys.exit(1) which let the terminal (in text mode) in an improper state, and does not save window position when using qt display.
=> Fix issue when selecting Quit in App with down key

mcu/bagl.py
In layouts like `nnbnn` normally the first and the last lines are displayed half. The other half is outside of the visible screen.
On the simulator, the first line wasn't drawn at all. The reason for this is that the y-coordinate of the bagl image is actually 16bit signed (may be negative) but is interpretated as 32bit unsigned on the simulator.
A coordinate of y=-5 becomes y=65531 which is outside the screen, so it's not drawn at all.
This fix casts the 32bit unsigned in the right value and the missing line is displayed again.
=> fixed wrong interpretation of 16bit signed coordinates

.gitignore, src/launcher.c, src/svc.c
This PR aimed at:
- ignoring core files in versioning in case of a crash
- replacing `getpagesize` by `sysconf(_SC_PAGESIZE)` which is preferred as part of posix
- mapping an extra page for the app's install parameters :
The install parameters of an app are mapped at the end of the `nvram` data of an app.
If this address happens to be the end of a page, speculos crashes when trying to access these parameters
ex: 
- `page_size = 0x1000`, elf size is `0x23d00` which means it will be mapped between `[0x40000000 - 0x40024000]` => as `_install_parameters` are mapped at the end of `_nvram_data` so `0x400023d00` they can be accessed ✔️ 
- `page_size = 0x1000`, elf size is `0x24000` which means it will be mapped between `[0x40000000 - 0x40024000]` => as `_install_parameters` are mapped at the end …
=> Fix install params mapping

build.Dockerfile, tests/apps/apdu_client.py, tests/apps/conftest.py, tests/apps/test_btc.py, tests/apps/test_ram_page.py, tests/apps/utils.py
The app fixture was requiring an extrafeature to be stopped.
In case of failure, the APDUClient was not properly killed,
thus leading to cascading test cases. This commit aims to
fix that.
=> [tests] improve 'app' fixture

src/bolos/cx_hash.h, src/emulate.c
Fix #139.
Unfortunately, there is no easy way to add test for this (but running an app).
=> syscalls: add cx_sha224_init

src/bolos/cx.h, src/bolos/cx_hash.h, src/bolos/cx_hmac.c, src/bolos/cx_hmac.h, src/bolos/cx_scc.c, src/bolos/os_bip32.c, src/emulate.c, src/emulate.h, src/emulate_blue_2.2.5.c, tests/syscalls/test_bip32.c
A Blue device with firmware 2.2.10-ee(l)(d) allow to call the `os_perso_derive_node_bip32_seed_key()` and `cx_hmac_sha512()` Bolos syscalls. However it is not possible for a Blue app running in Speculos, although the code for these syscalls is emulated for LNS/LNX. The syscall interface to these emulated functions is missing in Speculos' Blue emulation. 
This PR adds the appropriate syscall interfaces to these 2 Bolos emulated functions.
All tests green.
=> LVFM-846: add missing syscall to Speculos' Blue emulation

src/bolos/os_bip32.c
get_seed_from_env returns a size_t, which cannot be negative.
=> bolos: remove useless check

src/bolos/cx_scc.c
=> Enabled missing code for hmac with CX_SHA512

mcu/seproxyhal.py
Before this patch, running a Nano X app in debug mode with `DEFINES += HAVE_PRINTF PRINTF=mcu_usb_printf` would fail almost immediately with this error:
```
01:48:04.533:seproxyhal: unknown tag: 0x5f
```
That "unknown tag" comes from this line in the nano x SDK:
https://github.com/LedgerHQ/nanox-secure-sdk/blob/master/src/os_io_seproxyhal.c#L1405
```
void mcu_usb_printc(unsigned char c) {
unsigned char buf[4];
#ifdef TARGET_NANOX
buf[0] = SEPROXYHAL_TAG_PRINTF;
```
its value is defined here:
https://github.com/LedgerHQ/nanox-secure-sdk/blob/master/include/seproxyhal_protocol.h#L173
`#define SEPROXYHAL_TAG_PRINTF 0x5F // <bytes to push to the printf buffer>`
...so in speculos I defined that tag (even though it's not a "general status") and enabled logging of the `PRINTF`s from my nano x …
=> recognize SEPROXYHAL_TAG_PRINTF and log from Nano X

.github/workflows/continuous-integration-workflow.yml
DockerHub is deprecated and credentials to the speculos image has been
(hopefully temporarily) revoked, making the next steps of the job fail.
=> ci: prevent failure if the push to DockerHub fails

.github/workflows/continuous-integration-workflow.yml, tools/deprecate-dockerhub.patch
I hope this warning will be read by speculos users, in order to make them update
the docker image URL in their scripts.
=> ci: add a warning when executing speculos.py from the Docker Hub image

mcu/bagl.py, mcu/display.py, mcu/headless.py, mcu/nanox_ocr.py, mcu/screen.py, mcu/screen_text.py, mcu/seproxyhal.py, speculos.py, src/bolos/bagl.c, tests/apps/resources/btc_getpubkey_nanox.json, tests/apps/test_btc.py
This PR is based on @dkremer-ledger work, PR #118 (thanks a lot to him!).
To put it short, on the Nano X there is no syscall to display text characters to the screen (because the screen is connected to the SE on a real device) and bitmaps are directly rendered. Some kind of OCR was introduced to reverse that process and tell which character is displayed. `--automation` and `--automation-port` are now working on the Nano X.
To test it:
```
$ ./speculos.py --log-level automation:DEBUG --automation-port 1238 --model nanox ./apps/nanox#btc#1.2#57272a0f.elf 
[*] speculos launcher revision: 78aaf57
[*] using SDK version 1.2
[...]
11:00:12.008:automation: broadcast {'text': 'Application\nis ready', 'x': 35, 'y': 20} to []
11:00:13.396:automation: broadcast {'text': 'Settings', 'x': 41, 'y': 35} …
```
=> Add support for automation to the Nano X

src/bolos/os_eip2333.c
As `path[i]` is an `unsigned int`, it cannot be greater than `0xffffffff`. So the check in function `cx_derive_child_sk` was not
needed, and triggered a warning in LGTM: https://lgtm.com/projects/g/LedgerHQ/speculos/snapshot/7839414ae493f551fbe0850bb249b7617cb46c2d/files/src/bolos/os_eip2333.c?sort=name&dir=ASC&mode=heatmap#L179
Remove this check to silence LGTM.
=> os_eip2333: remove unnecessary condition

src/CMakeLists.txt
When using QEMU 5.2.0 (from Debian 11) or 6.0.0 (from Arch Linux), speculos fails to start, with:
qemu-arm-static: /speculos/build/src/launcher: Error mapping file:
Cannot allocate memory
This error comes from QEMU's loading of ELF files: https://github.com/qemu/qemu/blob/v5.2.0/linux-user/elfload.c#L2869
Using `qemu-arm-static -d trace:* build/src/launcher` to debug this issue leads to:
203@1623857052.685085:target_mmap start=0xff000000 len=0x11aaa94
prot=0x0 flags=0x4032 fd=-1 offset=0x0
As 0xff000000 + 0x11aaa94 = 0x1001aaa94 overflows the capacity of 32-bit integers, it is normal that QEMU fails to allocate memory. Fix this by moving the launcher to a lower address.
=> launcher: map the launcher at a lower address to prevent int overflow

mcu/apdu.py
https://lgtm.com/ reports "'0.0.0.0' binds a socket to all interfaces." in:
self.s.bind((host, port))
because `ApduServer` is only used with 0.0.0.0:
apdu = apdu_server.ApduServer(host="0.0.0.0", port=args.apdu_port)
Like commit f2e0e0eac6f7 ("mcu: remove LGTM "'0.0.0.0' binds a socket to all interfaces" alerts"), add a comment to silence LGTM.
=> mcu: silence LGTM error about binding to 0.0.0.0

api/api.py, speculos.py
Currently, launching Speculos leads to a big warning message:
* Serving Flask app "api.api" (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
This is because Speculos uses the web server embedded in Flash, instead of a real web server (Apache, NGINX...) and a WSGI service.
Following https://flask.palletsprojects.com/en/2.0.x/config/ , enable *development* environment.
Moreover when running with `FLASK_DEBUG=on`, an exception is raised in werkzeug (the web server used by Flask):
File "/usr/lib/python3/dist-packages/werkzeug/_reloader.py", line 330, in run_with_reloader
signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
File "/usr/lib/python3.9/signal.py", line 47, in signal …
=> api: run Flask in development mode

mcu/seproxyhal.py
The U2F application calls `io_seproxyhal_request_mcu_status` (in https://github.com/LedgerHQ/app-u2f/blob/561adacce62082875e89f241acbcb59a3c14639e/src/main.c#L1871 ), which emits a `SEPROXYHAL_TAG_REQUEST_STATUS` packet (in https://github.com/LedgerHQ/nanos-secure-sdk/blob/2.0.0-1/src/os_io_seproxyhal.c#L124-L132 ).
Currently, this call makes speculos to stop immediately, with:
seproxyhal: unknown tag: 0x52
Ignore `SEPROXYHAL_TAG_REQUEST_STATUS` packets, as they are not necessary for the app to operate correctly.
=> mcu/seproxyhal: ignore io_seproxyhal_request_mcu_status

docs/installation/build.md
#170 adds a REST API that uses flask_restful.
This PR updates the documentation and adds python3-flask-restful in the requirements.
=> Add flask_restful in Speculos requirements

mcu/display.py
Screenshot API requests may return invalid images due to a race condition on the screenshot image update.
This happens frequently especially when recording a GIF.
Here is an example of invalid screenshot during a GIF recording:
=> Fix screenshot race condition

docs/installation/build.md
cmake is required to run the build commands.
While at it, split the long line in order to improve the rendered documentation on https://speculos.ledger.com/installation/build.html and document the supported Linux distributions on which the command line works. This command has been tested with containers `docker.io/library/debian:10-slim` and `docker.io/library/ubuntu:18.04`.
=> docs: add cmake to the Linux build requirements

src/vnc/CMakeLists.txt
When trying to build speculos using `pip` in a minimal container, `cmake` complains about not being able to find a C++ compiler:
cmake --build build
[  1%] Creating directories for 'vnc_server'
[  1%] No download step for 'vnc_server'
[  2%] No update step for 'vnc_server'
[  3%] No patch step for 'vnc_server'
[  4%] Performing configure step for 'vnc_server'
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:3 (project):
No CMAKE_CXX_COMPILER could be found.
Tell CMake where to find the compiler by setting either the …
=> src/vnc: mark VNC Server sub-project as C-only

tests/apps/conftest.py
The regular expression which was used to find applications in apps/ used
an unescaped dot in `.elf`. This matched any character instead of a dot,
which is a bug. Add a backslash character to fix this bug.
While at it, add `^` and `$` characters to the regular expression, and
use `[^#]+` to match the application name, as it is not allowed to
contain any `#` character.
While at it, make `list_apps_to_test` fail when it encounters a file in
`apps/` which does not match the regexp if it should. This helps
detecting possible issues with the regexp, if it is for example too
restrictive.
Last but not least, a `f` was missing when the error which produces the
message `"The TestClass {metafunc.cls} does not have a correct 'app_names' attribute."`
occurs. This makes pytest reports messages such as: …
=> tests/apps: make conftest more robust

src/bolos/os.c
In the event of a `os_lib_call`, the caller `try_context` can be erased by the `try_context` of the callee as its main is likely to be in a `TRY/CATCH` block. After returning to the caller with a `os_lib_end` if the call triggers an exception of some sorts (`THROW`), the `longjump` performed to branch to the `try_context` stack pointer uses a wrong address (the one of the stack pointer's callee's `try_context`) This commit aims at saving/restoring the caller's context after a call to `os_lib_call` to prevent the issue
=> Save caller try_context to avoid anarchic longjmps

src/vnc/vnc_server.c
On Ubuntu 21.04, `select()` now uses `pselect6` syscall. This makes `vnc_server` crash because of its seccomp filter. `strace` shows:
bind(4, {sa_family=AF_INET6, sin6_port=htons(5900),
sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::", &sin6_addr),
sin6_scope_id=0}, 28) = 0
listen(4, 32)                           = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE],
sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f559ea63040},
{sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
pselect6(5, [0 3 4], NULL, NULL, {tv_sec=0, tv_nsec=5000000},
NULL <unfinished ...>) = ?
+++ killed by SIGSYS (core dumped) +++
Fix this by allowing the syscall.
=> vnc_server: allow pselect6 syscall

mcu/nanox_ocr.py
Function `get_font_char` does not do anything and is not used in Speculos code.
=> mcu/nanox_ocr: remove function get_font_char

docs/installation/build.md
Since commit 0c1bbcf00b30 ("add a REST API server") Speculos depends on
PIL or Pillow to provide a module for `from PIL import Image`. Moreover
it uses `requests` to interact with the embedded HTTP server. Update
the dependencies command line accordingly.
NB. The Python dependencies used by the Docker container are listed in
`Pipfile` and were updated in commit 1ecedc8eefe6 ("update pip files").
=> docs/installation/build: install python3-pil and python3-requests too

speculos/api/api.py, speculos/main.py, speculos/mcu/display.py
*This PR depends on https://github.com/LedgerHQ/speculos/pull/212 as this works was done after it.*
When the API server fails to start, for example when there is already a server bound to TCP port 5000, Speculos continued to run. This is because the Flask web server was launched in a separate thread and propagating a failure is not straightforward.
Introduce a new `socketpair` to signal Speculos' main event loop that the API server stopped and that Speculos should exits.
=> speculos/api: plug the API to the notifiers mechanism

setup.py
Speculos works fine with Python 3.6, but uses `dataclasses`, which was integrated in Python 3.7 and is available as "backport" in a package https://pypi.org/project/dataclasses/#description
=> setup: support Python 3.6

CMakeLists.txt, setup.py
Include `CTest` in order to add `BUILD_TESTING` variable. This seems to
be a documented way to add tests in a cmake project:
https://cmake.org/cmake/help/latest/module/CTest.html#module:CTest
Put cmocka and `tests/syscalls` in `if (BUILD_TESTING)` conditional
blocks, in order to only use them when tests are being built.
When building the Python packages, C tests are not needed, so they can
be skipped, using `-DBUILD_TESTING=0`.
=> cmake: only build tests when BUILD_TESTING is enabled

CMakeLists.txt, clang-armv7m.cmake, gcc-arm.cmake, src/CMakeLists.txt
Some time ago I wanted to build Speculos with `clang` in order to see whether some clang-specific warnings triggered with Speculos's C code. It was quite difficult because the current cmake configuration expects to be using `arm-linux-gnueabihf-gcc` in several places.
This Pull Request:
* enables using a toolchain file as documented in https://cmake.org/cmake/help/v3.21/manual/cmake-toolchains.7.html#cross-compiling ;
* introduces `clang-armv7m.cmake` and `gcc-arm.cmake` which can be used to build Speculos (usage is documented as the beginning of these files) ;
* propagates the toolchain configuration in the external sub-projects (OpenSSL and cmocka) ;
* makes the build configuration compatibles with clang (clang does not know about `-mthumb` and `-Ttext-segment`) ;
* ... while keeping …
=> Enable building Speculos with clang

src/emulate_2.0.c
In SDK 2.0, the retid mechanism is no longer used. But `emulate_2_0` still used a local variable, which is not initialized. This leads to clang reporting many warnings such as:
speculos/src/emulate_2.0.c:180:5: warning: variable 'retid' is used
uninitialized whenever switch case is taken [-Wsometimes-uninitialized]
SYSCALL3(cx_bn_mod_u32_invert, "(%u, %u, %u)", uint32_t, r, uint32_t, a,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
speculos/src/emulate.h:231:8: note: expanded from macro 'SYSCALL3'
case SYSCALL_##_name##_ID_IN: {                                              \
^~~~~~~~~~~~~~~~~~~~~~~
<scratch space>:118:1: note: expanded from here
SYSCALL_cx_bn_mod_u32_invert_ID_IN
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fix this by removing `retid` from `emulate_2_0`.
=> src/emulate_2.0: remove retid variable

MANIFEST.in, setup.py, tools/update_setup_version_from_git.sh
This prepares the publication of Speculos package on PyPI and TestPyPI. The idea is to tag the merge commit of this PR with `0.1`. Then the version of each merge commit of the master branch can be computed with:
```sh
LAST_TAG="$(git describe --tags --abbrev=0)"
COUNT="$(git rev-list --count "${LAST_TAG}..HEAD")"
VERSION="${LAST_TAG}.${COUNT}"
```
(For example the merge commit 10 commits after tag `0.1` would be version `0.1.10`.
Introduce `tools/update_setup_version_from_git.sh` to do this in `setup.py`. This file may then be called from GitHub Action to update `setup.py` before creating the Python package (I will update https://github.com/LedgerHQ/speculos/pull/220 accordingly once this PR is discussed/merged).
=> Introduce version 0.1

.github/workflows/continuous-integration-workflow.yml
Use commands from https://packaging.python.org/tutorials/packaging-projects/ to build the Python package and push it to TestPyPI at each commit on `master`.
This requires the C code of Speculos to be part of the source tarball ("sdist"). Modify `MANIFEST.in` accordingly.
As this also requires that `setup.py` no longer builds the C tests, this PR depends on https://github.com/LedgerHQ/speculos/pull/219.
=> Publish Speculos on TestPyPI in the CI

speculos/__main__.py, speculos/main.py
Currently it is possible to run Speculos with `python -m speculos.main`. This is not very intuitive, and leads to a warning:
```text
/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'speculos.main' found in sys.modules after import of
package 'speculos', but prior to execution of 'speculos.main'; this may result in unpredictable behaviour
```
https://github.com/LedgerHQ/speculos/pull/229 fixed this by removing the `from . import main` from `__init__.py` but this is problematic: even though `import speculos.main ; speculos.main.main()` still works, `import speculos ; speculos.main.main()` does not.
This PR fixes this issue in a cleaner way, by introducing a `__main__.py` file in `speculos/`. While at it, it removes the execution ability from `main.py`.
=> Execute speculos with python -m

speculos/api/api.py, speculos/api/static/index.html, speculos/client.py, tests/api/test_api.py
Server-Sent Events (SSE) enables a client to receive automatic updates from a
server via an HTTP connection. It is now part of HTML5 since a few years and
supported by all browsers but IE:
- https://www.w3.org/TR/eventsource/
- https://html.spec.whatwg.org/multipage/server-sent-events.html
If fixes a bug where some events were received twice by the web page on Chrome
and Firefox.
=> Fix event stream

tools/update_setup_version_from_git.sh
As Speculos git repository does not use tags currently, the reference of the version of the Python package is `setup.py`.
Change the way versions are computed so that it is `x.y.z` where the `setup.py` in git contains `x.y.0` and `z` is computed by counting the number of commits since the last change of the version line.
Suggested-in: https://github.com/LedgerHQ/speculos/issues/230
=> tools/update_setup_version_from_git: no longer rely on git tag to modify the version

speculos/client.py
The ApduException class is missing information about the returned APDU data. This PR adds it to the constructor in order to enable handling the error in a more precise way (in my case, I return a special SW that is not an error, but rather a request for the client side; therefore, it is crucial to have access to the apdu data).
=> Added 'data' argument to ApduException; made args mandatory

speculos/mcu/automation.py
This path depends on a user-provided value.
This alert was introduced in0c1bbcf3 months ago in/mcu/automation.py
The path comes from the command-line and that's expected.
=> remove LGTM alert

src/launcher.c
In latest FW versions, the application RAM (.bss + stack) is zeroized at startup
=> Zeroize app ram in latest FW versions

speculos/client.py, tests/unit/test_client_Api.py, tests/unit/test_client_SpeculosClient.py
```
Traceback (most recent call last):
File "./demo.py", line 125, in <module>
client.stop()
File "/speculos/speculos/client.py", line 224, in __exit__
self.stop()
File "/speculos/speculos/client.py", line 213, in stop
self.close_stream()
File "/speculos/speculos/client.py", line 76, in close_stream
self.stream.close()
AttributeError: 'NoneType' object has no attribute 'close'
```
=> client: fix error when closing stream

tools/debug.sh
Our tools are named slightly differently, so this makes it easier to change without needing to fork so hard.
=> Add env vars to allow different GDB and ELF

speculos/main.py
Modified the default SDK for Nano S to be version 2.1.0 instead of 2.0.0
cxlib for it already existing since #250
=> Default to SDK 2.1.0 for LNS

src/CMakeLists.txt, src/bolos/cx_aes_sdk2.c, src/bolos/cx_ec.c, src/bolos/cx_ec.h, src/bolos/cx_ecpoint.c, src/bolos/cx_ed25519.c, src/bolos/cx_montgomery.c, src/bolos/cx_scc.c, src/bolos/cx_twisted_edwards.c, src/bolos/cx_weierstrass.c, src/bolos/os.c, src/emulate.c, src/emulate.h, src/emulate_1.2.c, src/emulate_1.5.c, src/emulate_1.6.c, src/emulate_blue_2.2.5.c, src/launcher.c
Add several compilation flags that check for format strings and qualifiers.
`-Werror` has also been added to forbid warnings during compilation.
=> Harden compilation flags

docs/user/usage.md
RunDocs is unable to resolve the relative path for `src/sdk.h` in the HTML generated documentation. Let's use an absolute path.
=> docs: use absolute URL for src/sdk.h

speculos/api/events.py
Werkzeug version >= 2.1 will raise if accessing  field whereas the request content is not declared as application/json.
So for a simple `get` with no embedded data but a trivial query arg (`/events?stream=True`), specifying to look for argument as values should do.
=> [fix][#282] 

.github/workflows/continuous-integration-workflow.yml
Latest merged [PR](https://github.com/LedgerHQ/speculos/pull/284) broke the CI: the python venv is not present in the last step, when uploading the new Speculos package.
This PR upload the venv as an artifact to use it in the last job.
We could use cache, but I'm not sure how the cache mechanism is updated with newer versions (which could easily break in Python, [see this issue](https://github.com/LedgerHQ/speculos/issues/282)) in GitHub, and generally I don't trust caches. I'm open to opinions.
=> [ci][fix] Sharing Python venv between build job and upload job

.github/workflows/continuous-integration-workflow.yml
The docker need the `speculos/resources/` directory to be created and present to work. This is created when performing a `pip install ` of Speculos, so this code move this step from the `build` step (where it wasn't that useful) to the `package_python` step.
=> [ci][fix] The docker image needs to embed ressource files

.github/workflows/continuous-integration-workflow.yml, .github/workflows/speculos-builder.yml, src/vnc/CMakeLists.txt
This reverts commit b64d28d2df793ad3733c9db1a6946331e6d94502 which seems to have
pushed linux/aarch64 docker images to ghcr.io (while linux/amd64 and aarch64
images were expected).
This commit was introduced by the PR #292 which add support for Mac M1 by adding
docker images for the AARCH64 architecture. However, it requires a more recent
version of build-push-action to be effective and upgrading to a new version
isn't straightforward.
=> Revert "Build Docker image wit Mac M1 chipset support"

Dockerfile, tools/debug.sh
When using gdb with Mac M1, disable gdbinit usage
=> disable gdbinit usage for Mac M1

src/bolos/cx_utils.h
Predefining NATIVE_64BITS leads to a redefinition if speculos source files are
built with cxlib:
https://github.com/LedgerHQ/nanox-secure-sdk/blob/86324f6a73e269c04f6a3e3cf41f6569a8cc6c6b/lib_cxng/include/lcx_common.h#L38
=> automatically define NATIVE_64BITS on 64-bit CPUs

src/bolos/cx_ec_domain.c
a small rookie mistake while adding the `goto error`
we can jump in error while the variables do no exist
=> fix: variables used before declaration

.codespell-ignore
codespell reports a false-positive mispelling:
speculos/mcu/screen.py:170: globalY ==> globally
Ignore this by adding this word to `.codespell-ignore`.
=> codespell: ignore globalY

Pipfile, Pipfile.lock
Pipfile was still using `python3.8` when the Dockerfile explicitely uses `python3.9`
Adding `pytest` as a dependency to run tests easily within the container
=> Update pip files and add pytest

speculos.py, speculos/main.py, src/bolos/os.c
In order to easily detect whether the emulated app exited successfully or not, it is necessary to use the exit `code` in the actual call to `_exit`.
This is not necessary in most cases as bolos ignores this exit code, but enables easier testing in CI: if the test calls `os_sched_exit` with a non-zero status, the CI can tell it failed directly.
=> Propagate app's exit status

src/emulate_lnsp_1.0.c
LNS+ emulation ended with an error if the syscall used was a 'common' one with other platforms, instead of forwarding the call to `emulate_common` like other platforms.
=> Fallback syscall emulation to common for LNS+

speculos/main.py
Do this instead of just loading the section itself.
Sections are just for linking purposes and not needed at runtime with a completely linked app. Segments (corresponding to program headers), on the other hand, are the actual important runtime data for what should be loaded. It is therefore more correct to load or not load whole sections than individual segments.
We have successfully tried out various linker tricks, in order to have things like properly initialized globals and relocations to reflect apps install-time address on the flash. This is a small step that makes it easier to use speculos which such experiments.
We would be happy to further improve speculos on this front, e.g. to make it load multiple program headers provided they are adjacent, or also load "hex" files (to be more …
=> Load entire segment containing `.text`

speculos/api/button.py, speculos/api/finger.py, speculos/mcu/seproxyhal.py, tests/api/test_api.py
This is necessary when OCR takes a lot of time:
- without this, many ticker events will be send during the OCR, which will lead to a timeout for responding on the app side.
- as ticker events might be dropped (if speculos thread is busy), then buttons and finger delay should take it into account.
Note that before this change, buttons and finger delay was also done after release which is not requested and probably not wanted. This is not the case anymore.
=> speculos: Avoid flooding app with tickers and fix button and touch wait delay

speculos/api/button.py
This delay was removed in 2c22a66dea1863e0f04b09896dfe112b68412eaf but sadly some tests are using it. So we rather re-adding it for now.
=> speculos: Restore delay after button press-and-release

.github/workflows/continuous-integration-workflow.yml
Linked to #230 
This PR allows to deploy on `pypi.org` as soon as we merge in `master`, with the last commit message containing `release`.
This will allow to install Speculos without the `--extra-index` argument, and allow tools using Speculos such as `ragger` to benefit from the same improvment.
=> Auto deployment from master when last commit message contains 'release'

sdk/bolos_syscalls_unified_sdk.h, src/bolos/endorsement.c, src/bolos/endorsement.h, src/emulate.h, src/emulate_unified_sdk.c, tests/syscalls/test_endorsement.c
Add support for new prototypes of `os_endorsement_get_public_key` and `os_endorsement_get_public_key_certificate`
=> Add the support for new prototypes of os_endorsement functions

README.md, docs/user/usage.md, setup.py
Not a big change, but I was mistakenly convinced that Speculos didn't support Ledger Stax given the description of the repo and the fact that it wasn't mentioned in the doc.
=> Add Stax mentions in the documentation and description

.github/workflows/continuous-integration-workflow.yml, README.md
Image URL in README is now hardcoded.
This avoids the need to `sed` before packaging Speculos in the CI. This feature was generating 'unclean' repository which resulted `setuptools_scm` to generate `<a>.<b>.<c+1>.dev0` versions instead of `<a>.<b>.<c>`.
The issue will be that now, on unmerged branches, the README will refer to this URL pointing to the GitHub pages, which could be out-of-date if changed.
However as a new deployment is performed as soon as the branch is merged on `master`, this is not a very potent problem.
=> Deployment fix

speculos/api/events.py, speculos/api/screenshot.py, speculos/mcu/display.py, speculos/mcu/screen.py, speculos/mcu/seproxyhal.py
Only publish screenshot content when the OCR is finished on Stax
Rework the take_screenshot to avoid recreating the image at every REST api refresh
=> Scarce screenshot publish

speculos/mcu/ocr.py, tests/syscalls/test_mpi_rng.c
The previous OCR fix broke some ci/tests made with API_LEVEL_1 built apps.
This PR make the OCR behave _almost_ like legacy one when not using loaded JSON fonts.
(almost because there are still w & h fields which was added to TextEvent fields)
=> Keep legacy behaviour

speculos/mcu/seproxyhal.py, src/bolos/bagl.c
Very similar to what was done here: a9f403302d027daf619bf04664093a87dc2e10ab
=> bagl.c/seproxyhal.py: Explicit BAGL custom seph tags and handle them properly

CHANGELOG.md, speculos/main.py, src/launcher.c
There's a null dereference occuring in `speculos` itself when passing in a *valid* application that does not contain the `C_bagl_fonts` symbol. This PR removes the offending call to `parse_fonts` if this symbol was not found.
=> fix: do not parse fonts if symbol not present

src/bolos/cx_utils.h, src/bolos/fonts_info.c, src/launcher.c
Make sure the variable **nb_bitmap_char** is initialized.
(this variable is needed later by **get_character_from_bitmap** function)
=> Make sure nb_bitmap_char is initialized

CHANGELOG.md, speculos/api/api.py, speculos/main.py
This leads to `DisplayNotifier` implementation-specific behaviors when the application exists - and the `SeProxyHal(IODevice)`  throws a `ReadError` (I guess it's also true for others `IODevice`).
I added a 10s timeout to avoid neverending `.join()` call.
=> [B2CA-1417] The Speculos API is not properly stopped when Speculos quits

README.md
Following recent SDK change, this is not true anymore.
Linked to https://github.com/LedgerHQ/ledger-secure-sdk/pull/472
=> README.md: Remove Pending review screen limitation

speculos/mcu/display.py, speculos/mcu/headless.py, speculos/mcu/nbgl.py, speculos/mcu/screen.py, speculos/mcu/seproxyhal.py, speculos/mcu/vnc.py
This changes allow to reduce app-boilerplate stax tests run time from 50s to 18s on my setup.
Note that this could be further reduced to 10s if using ragger configuration BACKEND_SCOPE="session".
=> speculos: Fasten graphics handling

CHANGELOG.md, speculos/api/api.py, speculos/api/helpers.py, speculos/main.py, speculos/mcu/automation.py, tests/python/api/test_api.py, tests/python/apps/test_btc.py, tests/python/mcu/test_automation.py
This was the cause of these annoying yellow warnings when running tests with Ragger or Speculos:
```
============================================================================ warnings summary =============================================================================
../../../.virtualenvs/ragger/lib/python3.10/site-packages/speculos/api/api.py:3
/home/lpascal/.virtualenvs/ragger/lib/python3.10/site-packages/speculos/api/api.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
import pkg_resources
../../../.virtualenvs/ragger/lib/python3.10/site-packages/pkg_resources/__init__.py:2832
/home/lpascal/.virtualenvs/ragger/lib/python3.10/site-packages/pkg_resources/__init__.py:2832: DeprecationWarning: Deprecated call …
```
=> Replacing deprecated 'pkg_resources' with 'importlib.resources'

CHANGELOG.md, speculos/api/finger.py, speculos/api/resources/finger.schema, speculos/client.py, speculos/mcu/screen.py
- In the API, the finger route can now receive `x2` and `y2` in addition to the required `x` and `y` position.
When they exists, `x2` and `y2` will be used as the **second** coordinates when the action is "press-and-release". They will be ignored in other cases.
- In the `SpeculosClient`, added a `finger_swipe` method in addition to the `finger_touch`. This new method takes the classic `x` and `y` but also a direction in [`up`, `down`, `right`, `left`] which automatically adds `x2` and `y2` to the API call.
**Pros**
- Higher level `swipe` method, handier than manually filling the `x2`, `y2`
**Cons**
- As is, the API does not propose direct control on `x2` / `y2` as the finger route allows (maybe adding optional `x2`, `y2` on `finger_touch` ? [EDIT] Added this, so that the client has all …
=> [add] Swipe capability on API + SpeculosClient

speculos/mcu/vnc.py
The goal of this PR is to fix the size of allocated buffer when redrawing vnc framebuffer
=> Fix size of allocated buffer when redrawing vnc framebuffer

src/bolos/nbgl.c
The goal of this PR is to fix potential inconsistency between the number of BPP set in the area and the number of BPP set in image "file" header. The Header is supposed to be the good one so the one in the area must be overriden.
=> Fix wrong display of some image files when BPP is not properly set in area

sdk/bolos_syscalls_unified_sdk.h, src/bolos/cx_crc.c, src/bolos/cx_crc.h, src/bolos/cxlib.c, src/bolos/cxlib.h, src/emulate_unified_sdk.c
Fixes https://github.com/LedgerHQ/speculos/issues/508
=> cx_crc_hw syscall support

src/bolos/cx_ec_domain.c, src/bolos/cx_ecpoint.c
Secp521r1 curve was previously disabled because speculos or its dependencies did not support it.
Now that it's the case, this PR enables the support of secp521r1 curve.
I have tested it with nist and wycheproof test vectors for ECDH.
=> Enable support for secp521r1

docs/_config.yml
The theme was hosted [on GitHub here](https://github.com/rundocs/jekyll-rtd-theme). Both the repository and the organisation no longer exist, for at least 2 weeks.
So I changed the theme for now. Maybe we could switch back if it reappears some day (?)
=> [fix] Doc theme 'rundocs/jekyll-rtd-theme' no longer exists

docs/conf.py, docs/requirements.txt
`CNAME` file is now included into the documentation build artifact, so that GH knows how to configure the DNS when it builds & deploys a new version of the Speculos documentation.
=> Automatic GH pages DNS configuration

speculos/main.py, src/bolos/os_signature.c, src/launcher.c
This PR allows to either load a PKI production certificate or a test certificate for testing purposes. By default, speculos will verify the certificate with a test key, one has to launch speculos with the argument `--pki-prod/-p` to verify a production certificate.
=> Enable the use of test key or prod key for PKI

.github/workflows/continuous-integration-workflow.yml
This will avoid that the last call uses system-wide packages
=> Activate the virtualenv instead of invoking its exec diretly

.github/workflows/continuous-integration-workflow.yml
Made a mistake in the first version of this PR: the needed right is `contents` not `deployments`!
Doc reference [here](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions).
=> [ci][fix] Allow the CI to make a deployment

CHANGELOG.md, speculos/main.py, src/bolos/default.c, src/bolos/os.c, src/emulate.h, src/launcher.c, src/launcher.h, tests/c/syscalls/test_os_global_pin_is_validated.c
It makes a part of "App storage functionality simplification" project ( https://github.com/LedgerHQ/ledger-secure-sdk/pull/865). 
But it seems to me that this change is quite independent, does not break the current stuff and so can be already merged . Unless you have some objections.
=> NVRAM data save and load support

CHANGELOG.md, speculos/main.py, speculos/mcu/display.py, speculos/mcu/headless.py, speculos/mcu/ocr.py, speculos/mcu/screen.py, speculos/mcu/screen_text.py, speculos/mcu/seproxyhal.py, speculos/mcu/struct.py, src/launcher.c
The goal of this PR is to make BAGL-based applications able to call NBGL-based libraries, or NBGL-based applications able to call BAGL-based libraries.
It is especially important for Exchange (Swap) Application.
The main fix consist in supporting two instances of GraphicalLibrary (BAGL and NBGL), instead of a single one
=> Fix BAGL applications calling NBGL libraries case

.github/workflows/continuous-integration-workflow.yml, .github/workflows/reusable_ragger_tests_latest_speculos.yml, speculos/main.py, src/bolos/default.c, src/launcher.c
NVRAM data save and load functionality is not implemented yet for Rust apps.
It is not obvious to do it as the linking/relocation is rather different from the C one. 
So let's do the hotfix at first and avoid doing those operations and also NVRAM write access boundary checking for Rust apps. 
To follow-up Rust NVRAM save and load support for Rust apps: https://github.com/LedgerHQ/speculos/issues/562
=> Fixing Rust apps crash and adding Speculos Rust tests

speculos/main.py, src/launcher.c
The goal of this PR is to fix a bug in Speculos, making it crash when using Rust apps or C plug-ins based on BAGL, not containing C_bagl_fonts
=> Do not rely on C_bagl_fonts to check whether an app is BAGL or NBGL

CHANGELOG.md, speculos/main.py
If the `fonts_addr` is `0`, it is replaced by the correct value.
But as this check / replace is made in a loop, it can become incorrect at the next iteration.
=> Incorrect font size/address computed when starting Speculos with a library

src/bolos/cx_mpi.c
This is an old behavior of modular exponentiation that has since been fixed in the OS.
=> Modular exponentiation with exponent 0 is allowed in BOLOS

CHANGELOG.md, src/bolos/fonts_info.c
The goal of this PR is to fix missing check of API level 25 when loading fonts. The result was an issue with Ragger (no strings found)
=> Fix missing check of API level 25 when loading fonts
