LedgerHQ/speculos

mcu/seproxyhal.py
=> seproxyhal: wait for a status before sending an event

src/emu_seproxyhal.c
=> seproxyhal: implement sys_io_seph_is_status_sent

Dockerfile, doc/usage.md, docker-compose.yml
Buttons are now available via tcp through port 42000.
=> Docker exposing new port for buttons api

doc/usage.md, docker-compose.yml, mcu/vnc.py, speculos.py, vnc/vnc_server.c
It should prevent MacOS Screen Sharing from closing the connection to the VNC server (#34).
=> support a VNC password through --vnc-password

.github/workflows/continuous-integration-workflow.yml, tests/apps/test_btc.py
It will ensure that the future sandbox doesn't break anything.
=> add VNC tests

doc/build.md
`mcu/automation.py` uses `import jsonschema`
=> Install python3-jsonschema too

mcu/bagl_glyph.py
We use these two glyphys a lot. It would be nice to have them included.
=> Missing left/right glyphs

doc/usage.md, mcu/screen.py, vnc/vnc_server.c
=> map down key as a shortcut for pressing both left and right keys

src/cx_ec.c, src/cx_ed25519.c, src/cx_ed25519.h
Ed25519 is the only curve supported for now.
=> add cx_ecfp_add_point() syscall

lgtm.yml, mcu/apdu.py, mcu/bagl.py, mcu/button_tcp.py, mcu/finger_tcp.py, mcu/screen.py, mcu/seproxyhal.py, vnc/winamp.py
https://lgtm.com/ is a free service that uses Semmle queries to find issues in the source code. It can analyze Python code directly, but needs some configuration (in `lgtm.yml`) to analyze C files.
I have tested the configuration file in this PR on https://lgtm.com/projects/g/niooss-ledger/lgtm-speculos/alerts/?mode=list
=> Add configuration for lgtm.com and fix various Python warnings

src/cx_aes.c
I still have to check whether this is a supported case on the actual device!
=> AES CBC decrypt: fix case when in & out alias

mcu/screen.py
This commit fix a problem occurring when using multiple screens, with different resolutions, and with current screen placed in such a way that default _absolute coordinate_ of 10,10 is in a non visible area...
Now, on first launch, the default coordinates used takes in account current screen geometry, and check for each launch that window will be fully visible in one of the available screens : if it is clipped, even a little bit, default coordinates (in current screen) will be used.
=> Fix invisible window when using multiple screens.

README.md
This helps following the automated code analysis.
=> Add codecov.io and lgtm.com badges to README

CMakeLists.txt, src/launcher.c
It should make troubleshooting a bit easier.
=> include last git commit hash in launcher.c

build.Dockerfile
s/openssl-1.1.1f/openssl-1.1.1k/g
=> fix build.Dockerfile

.github/workflows/continuous-integration-workflow.yml, .github/workflows/speculos-builder.yml, docs/dev/ci.md, docs/user/docker.md
=> ci: make use of GitHub packages

.github/workflows/speculos-builder.yml
Warning: Unexpected input(s) 'file', valid inputs are ['entryPoint', 'args', 'username', 'password', 'registry', 'repository', 'tags', 'tag_with_ref', 'tag_with_sha', 'path', 'dockerfile', 'target', 'always_pull', 'build_args', 'cache_froms', 'labels', 'add_git_labels', 'push']
=> ci: fix invalid GitHub workflow

build.Dockerfile
Otherwise the tests against the REST API PR (#170) fail.
=> update build.Dockerfile for the REST API

api/api.py, api/resources/button.schema, api/resources/finger.schema, api/swagger.yaml, api/swagger/swagger.json, docs/user/api.md, tests/api/test_api.py
It makes no sense to pass parameters in the query for POST requests.
=> update api button

mcu/seproxyhal.py, mcu/usb.py, speculos.py
Being able to simulate the U2F transport is useful when testing the U2F application.
=> Switch to the U2F-over-USB transport protocol using 'speculos --usb u2f'

docs/user/usage.md, tools/gif-recorder.py
=> tools: add gif-recorder.py

speculos.py
As part of creating a proper Python package for Speculos, the Pull Request https://github.com/LedgerHQ/speculos/pull/120 created a `main` function in its first commit.
This change is useful as-is, without waiting for a proper solution for the problem of Python package creation. Therefore I took this commit, rebased it on `master` and now create this Pull Request in order to integrate it.
=> Add main() function and fix logging

speculos.py
This is reported by pylint as:
R1707(trailing-comma-tuple) Disallow trailing comma tuple
=> Remove trailing commas in Python code

mcu/automation.py, mcu/bagl.py, mcu/nanox_ocr.py, mcu/seproxyhal.py, tests/mcu/test_automation.py
This is already the case on Nano S.
=> mcu: send one text event per line on Nano X

api/api.py
It avoids HTTP client being blocked. Eg.
```
with requests.post(f"{API_URL}/apdu", json={"data": data}) as r:
print("do stuff even in the response isn't available yet")
assert response.status_code == 200
```
=> api: on /apdu, send HTTP headers before having the exchange response

speculos/mcu/screen_text.py
Fixes:
- `--display text` doesn't work anymore
- the last line from the screen is missing
- the screenshot image is update too often
=> update text screen

.github/workflows/continuous-integration-workflow.yml, setup.py
Adding some `pytest` flags to generate Python code coverage artifact
=> [add] Coverage for Python code

docs/user/usage.md
This updates the usage documentation with latest SDK.
=> docs: update usage with newer SDK

.github/workflows/continuous-integration-workflow.yml
=> [ci][fix] Docker build need the Dockerfile

src/vnc/vnc_server.c
It fixes recent test failures.
=> vnc: fix a delay on network connection

sdk/bolos_syscalls_2.0.h, src/bolos/bagl.c, src/bolos/bagl.h, src/emulate_1.2.c, src/emulate_2.0.c, src/emulate_lnsp_1.0.c, src/emulate_unified_sdk.c
=> Support for 'screen_clear' syscall

.gitignore, CHANGELOG.md, src/bolos/os.c, src/sdk.h, src/svc.c
Fix os_lib_call for API_LEVEL_9 and API_LEVEL_10 and improve behavior to avoid having this issue again
=> Fix os_lib_call for API_LEVEL_9 and API_LEVEL_10

speculos/mcu/bagl.py, speculos/mcu/headless.py, speculos/mcu/screen.py, speculos/mcu/screen_text.py
This PR fixes an issue occurring on Blue: this device uses _old_ fonts and doesn't know how to handle transparent pixels.
The corresponding ticket is here: https://ledgerhq.atlassian.net/browse/VG-16034
=> Fix issue VG-16034 - Glitch on Blue Vault app

speculos/mcu/screen.py
This class `QtScreenNotifier` inherits from `DisplayNotifier`, but the order of property instantiation between the base class and the child class is a bit tricky, and was leading to a property not being defined when used.
=> Fix faulty `QtScreenNotifier` instantiation

tests/c/test_environment.c
Fixes https://github.com/LedgerHQ/speculos/issues/455
=> bugfix: a declaration is not a statement

CHANGELOG.md, speculos/api/events.py, speculos/mcu/bagl.py, speculos/mcu/display.py, speculos/mcu/nbgl.py, speculos/mcu/ocr.py, speculos/mcu/seproxyhal.py, speculos/observer.py, tests/python/api/test_api.py
Fix https://github.com/LedgerHQ/speculos/issues/465
=> ocr: Fix screen content reset mechanism

CHANGELOG.md
=> Update CHANGELOG to v0.9.4

CHANGELOG.md
=> Changelog for v0.9.7

speculos/main.py
remove redundant word in comment
=> chore: remove redundant word in comment

CHANGELOG.md, Dockerfile, Pipfile, Pipfile.lock, pyproject.toml, speculos/api/api.py
In the context of the DMK sample app (url: https://app.devicesdk.ledger.com/) 
we have added the speculos transport for communicating with it but within this app we had the issue regarding the CORS. 
So I added a new addon to the flask server for authorizing all the CORS.
=> [NOISSUE] Set unrestricted CORS for speculos API

CHANGELOG.md, speculos/api/api.py, speculos/main.py, speculos/mcu/seproxyhal.py, src/emulate_unified_sdk.c, src/launcher.c, src/svc.c
- Remove unneeded logs
- Fix `logger.warn` deprecated api
- Add `-S/--silent` option to limit _werkzeug_ logs and remove timestamp from logs
- Add `-f/--finger` to log the Finger press positions
=> Cleanup logs

src/bolos/cx_ecpoint.c
=> Add x25519 support

.github/workflows/continuous-integration-workflow.yml, CHANGELOG.md, speculos/mcu/apdu.py, speculos/mcu/screen.py
Add the navigation on Stax/Flex using the keyboard
Automatically find an available APDU port, if the default one is already in-use
=> Small improvements
